### ISSUE TITLE
can't get kanban to work in remnote

### ISSUE THREAD

**Issue by MaruSeru67** [browneyedsoul/RemNote-Kanban#1]
I have followed the instructions:
- highlight items I want in the kanban boad
- type / and then kanban
- select the kanban plugin

nothing happens.

Using windows desktop remnote app

**Comment by MaruSeru67** [comment]
ooops
I just tried something else - it works lol

So you don't highlight what you want in the board - you just put your cursor on the rem that will be the kanband - can be a parent rem- and it will auto generate the board.  NICE.  case closed.

**Comment by browneyedsoul** [comment]
Thank you for confirming! I hope you enjoy it :)
